name = "proxy-apy-bridgesimpe"
main = "src/worker.js"
compatibility_date = "2025-01-01"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "api.tonyml.com/api/*", zone_name = "tonyml.com" },
  { pattern = "api.tonyml.com",       zone_name = "tonyml.com", custom_domain = true }
]

[build]
command = "npm install"

[observability]
enabled = true
[observability.logs]
enabled = true

[vars]
ENVIRONMENT = "production"
LOG_LEVEL    = "info"

# wrangler secret put API_KEY
